#!/usr/bin/env python3
"""Per-dataset downbeat CMLt, ours against Beat This, as a pgfplots figure.

Reads the per-piece CSVs written by make_tables.py's score stage and writes
paper/perdataset.tex, which the paper \\input{}s inside a figure environment.
pgfplots rather than an image so the labels are typeset by LaTeX itself and match
the body text exactly.

Preamble needs:
    \\usepackage{pgfplots}
    \\pgfplotsset{compat=1.18}
"""
import csv, os
from collections import defaultdict
import numpy as np

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(REPO, "paper", "results")
KEY = "CMLt_downbeat"
FKEY = "F-measure_downbeat"
NO_DOWNBEAT = {"simac", "smc"}          # no downbeat annotations to score against


def rows(p):
    return list(csv.DictReader(open(p)))


ours, bt = rows(f"{OUT}/cv_ours.csv"), rows(f"{OUT}/cv_bt.csv")
per = defaultdict(lambda: ([], [], [], []))
for ro, rb in zip(ours, bt):
    if ro["dataset"] in NO_DOWNBEAT or ro[KEY] in ("", "nan"):
        continue
    per[ro["dataset"]][0].append(float(ro[KEY]))
    per[ro["dataset"]][1].append(float(rb[KEY]))
    per[ro["dataset"]][2].append(float(ro[FKEY]))
    per[ro["dataset"]][3].append(float(rb[FKEY]))

data = []
for ds, (a, b, fa, fb) in per.items():
    a, b = np.array(a) * 100, np.array(b) * 100
    df = (np.array(fa) - np.array(fb)).mean() * 100
    data.append((ds, b.mean(), a.mean(), (a - b).mean(), len(a), df))
data.sort(key=lambda r: r[3])           # ascending, so the largest gain lands on top

poolb = np.concatenate([np.array(per[d][1]) for d in per]) * 100
poolo = np.concatenate([np.array(per[d][0]) for d in per]) * 100
poolfa = np.concatenate([np.array(per[d][2]) for d in per]) * 100
poolfb = np.concatenate([np.array(per[d][3]) for d in per]) * 100
pooled = (poolo.mean() - poolb.mean())
pooledf = (poolfa - poolfb).mean()

# Row 0 is the pooled result, row 1 a spacer, then the datasets in sorted order.
entries = [("all", poolb.mean(), poolo.mean(), pooled, len(poolo), pooledf), None] + data
labels, theirs, mine, deltas, fdeltas = [], [], [], [], []
for i, e in enumerate(entries):
    if e is None:
        labels.append("")
        continue
    ds, b, o, d, n, df = e
    labels.append(f"{ds.replace('_', chr(92) + '_')} ({n})")
    theirs.append((i, b)); mine.append((i, o))
    deltas.append((i, d)); fdeltas.append((i, df))

coords = lambda pairs: " ".join(f"({v:.2f},{i})" for i, v in pairs)
tex = rf"""% generated by paper/make_figure.py -- do not edit
\begin{{tikzpicture}}
\begin{{axis}}[
  xbar, width=0.78\columnwidth, height=3.05in,
  bar width=2.6pt, bar shift=0pt,
  enlarge y limits={{abs=0.55}},
  xmin=0, xmax=118, xtick={{0,20,40,60,80,100}},
  ytick={{{",".join(str(i) for i in range(len(labels)))}}},
  yticklabels={{{",".join("{" + l + "}" for l in labels)}}},
  tick label style={{font=\scriptsize}},
  xlabel={{downbeat CMLt}}, xlabel style={{font=\small, yshift=2pt}},
  axis y line*=none, axis x line*=bottom,
  xmajorgrids, grid style={{gray!25, line width=0.3pt}},
  legend style={{font=\scriptsize, draw=none, fill=none,
                 at={{(0.42,1.02)}}, anchor=south, legend columns=2,
                 /tikz/every even column/.append style={{column sep=6pt}}}},
  % xbar draws two swatches per entry by default; one filled rectangle is enough
  legend image code/.code={{\draw[#1, draw=none]
      (0cm,-0.055cm) rectangle (0.22cm,0.055cm);}},
  clip=false,
]
\addplot[fill=blue!62!black, draw=none, bar shift=-1.7pt] coordinates {{{coords(mine)}}};
\addplot[fill=black!28, draw=none, bar shift=1.7pt] coordinates {{{coords(theirs)}}};
\legend{{ours, Beat This}}
"""
for i, d in deltas:
    color = "blue!62!black" if d > 0 else "black!45"
    tex += (f"\\node[anchor=west, font=\\scriptsize, text={color}] "
            f"at (axis cs:104,{i}) {{${d:+.1f}$}};\n")
tex += (r"\node[anchor=west, font=\scriptsize, text=black!60] "
        "at (axis cs:104,17.9) {$\\Delta$};\n")
tex += "\\end{axis}\n\\end{tikzpicture}\n"

with open(f"{REPO}/paper/perdataset.tex", "w") as fh:
    fh.write(tex)
print(f"  wrote paper/perdataset.tex   "
      f"{sum(1 for d in data if d[3] > 0)}/{len(data)} positive, pooled {pooled:+.2f}")
